language: python
python:
  - 2.6
  - 2.7
  - 3.3
  - 3.4
before_install:
  - lsb_release -a # get info on the operating system
  - sudo apt-get update
  - sudo apt-get install -qq gfortran
  - sudo apt-get install -qq libgeos-3.2.2 libgeos-dev libgeos-c1
  - pip install --upgrade pip
  - pip install --upgrade setuptools
  - pip install wheel
  - git clone https://${GH_TOKEN}@github.com/obspy/wheelhouse.git /tmp/wheelhouse
  ### wheel building/upload start
  - cd /tmp
  - mkdir wheelhouse-build
  - sudo apt-get build-dep --ignore-missing -qq -y python-scipy python-suds python-lxml python-sqlalchemy python-m2crypto python-gdal
  - pip wheel ${WHEEL_BUILD_ARGS} numpy==$NUMPY_VERSION scipy==$SCIPY_VERSION matplotlib==$MATPLOTLIB_VERSION
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build numpy==$NUMPY_VERSION
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build scipy==$SCIPY_VERSION
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build matplotlib==$MATPLOTLIB_VERSION
  - pip wheel ${WHEEL_BUILD_ARGS} lxml sqlalchemy m2crypto PyYAML pyproj
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build lxml sqlalchemy m2crypto PyYAML
  - pip wheel ${WHEEL_BUILD_ARGS} gdal
  - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build gdal
  # build modified basemap package with the large data files stripped (which we dont use in testing anyway)
  # geos link fix is included in basemap master now
  ### - pip wheel ${WHEEL_BUILD_ARGS} https://github.com/megies/basemap/archive/v1.0.7_geos_link_fix__no_high_res.zip
  ### - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build basemap
  ### - pip wheel ${WHEEL_BUILD_ARGS} suds-jurko
  ### - pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build suds-jurko
  - if [ "${TRAVIS_PYTHON_VERSION:0:1}" == '2' ]; then pip wheel ${WHEEL_BUILD_ARGS} suds; fi
  - if [ "${TRAVIS_PYTHON_VERSION:0:1}" == '2' ]; then pip install --upgrade --use-wheel --no-index --find-links=/tmp/wheelhouse-build suds; fi
  - pip wheel ${WHEEL_BUILD_ARGS} --no-deps obspy || echo "skipping obspy"
  ### wheel building end
  - cd /tmp/wheelhouse/
  - git config --local user.email "travis@travis-ci.org"
  - git config --local user.name "travis-ci"
  - git pull
  ### wheel upload start
  - rm -f *-py${TRAVIS_PYTHON_VERSION//.}-*.whl *-py${TRAVIS_PYTHON_VERSION:0:1}-*.whl
  - rm -f *-cp${TRAVIS_PYTHON_VERSION//.}-*.whl
  - mv -n /tmp/wheelhouse-build/* /tmp/wheelhouse/
  - git add --all -v .
  - git diff --exit-code --staged && exit 0 || echo  # exit if no staged changes otherwise continue
  - git commit -m "Uploading new wheels"
  - git push --quiet origin master
  ### wheel upload end
  - exit 0
install:
  - exit 0
env:
  global:
    - secure: JiBG/vFGw/23q6Y/Sbel35EtqLSl+ehuKBGjrLJtUZFBFxRnbcZvqgDXjC+UpyoPhECMfin/boxvT0nG2p0n3x5Gtp2RyN2ue+U2G5c0ECxe+MTDntBYn2lC6quoIh568uj+gcdLc4Dq2Px9aM0cfQSEBd4TO+ENMgg4MRnEMg0=
    - WHEEL_BUILD_ARGS='-vvv --use-wheel --find-links=/tmp/wheelhouse --allow-all-external --wheel-dir=/tmp/wheelhouse-build --allow-insecure matplotlib --allow-insecure basemap --allow-unverified basemap'
    - NUMPY_VERSION=1.8.2
    - SCIPY_VERSION=0.14.0
    - MATPLOTLIB_VERSION=1.3.1
script:
  - exit 0
notifications:
    email: false
